### ISSUE TITLE
copycols=false

### ISSUE THREAD

**Issue by jtrakk** [xiaodaigh/DataConvenience.jl#5]
Nearly always when I'm using DataFrames functions, I pass `copycols=false` for the large speed boost. I am not concerned about this reducing safety because I never mutate columns in place. 

I propose

```jl
transmute(df, args...) = transform(df, args...; copycols=false)
```

**Comment by xiaodaigh** [comment]
transmute only keep the columns used in args right? I don't think this is relevant here. Please re-open if u can clarify what's happening.
