### ISSUE TITLE
Find an ArgumentError

### ISSUE THREAD

**Issue by Antonio-Nappi** [xiaodaigh/DataConvenience.jl#6]
Hello everyone, I'm newbie in Julia so sorry if it is a trivial question.
I've created my Dataframe with:
```
using DataConvenience
using DataFrames
df = DataFrame(A = 1:4, B = 2:2:8)
```
If I try to plot the correlatation, using the dfcor function, it rises an 

> ArgumentError : Elements of ["A","A"] must be unique

What am I doing wrong?

**Comment by xiaodaigh** [comment]
I haven't used the function in a while and the DataFrames API has changed quite a bit. Let me check. I should add a test for it

**Comment by Antonio-Nappi** [comment]
Ok, thank you very much.

**Comment by xiaodaigh** [comment]
it's working on the latest versioin being submitted. should be ready in a couple of days
